.github/workflows/upstream-build.yml
west.yml

Add a workflow to verify that it's possible to fetch the Silabs HAL tree and to build a Bluetooth sample agains a Silabs board using the latest upstream main tree. Run the workflow at 5:15 UTC every day.

github: workflows: Add upstream build workflow

---

boards/silabs/radio_boards/siwx917_rb4338a/siwx917_rb4338a.yaml
dts/arm/silabs/siwg917.dtsi

Fix the unit path definitions for flash and RAM, and make sure the board
yaml file is in sync with DTS.

silabs: siwg917: Fix memory definitions

---

west.yml

Upstream CI checks, as well as our own daily build show green, so update to the latest upstream revision.

manifest: Update to latest upstream main branch

---

.github/workflows/compliance.yml

Disable the KconfigHWMv2 check in the compliance workflow. This should work, but right now it seems broken in that it doesn't seem to recognize valid SoC Kconfig symbols in the zephyr-silabs soc directory.
This is (hopefully) just a temporary workaround, but it's better than having the compliance check fail and cause unnecessary noise for pull requests.

github: compliance: Disable KconfigHWMv2 check

---

.clang-format
.editorconfig
.github/workflows/compliance.yml
.gitignore
.gitlint
.yamllint

Add compliance check configuration files from the Zephyr main tree, and make sure the necessary python dependencies are installed (this is also taken from the main tree compliance workflow).

github: workflows: Improve compliance check

---

dts/arm/silabs/siwg917.dtsi
soc/silabs/silabs_siwx917/siwg917/soc.h

Include si91x_device.h from soc.h. This is the device header used by the Wiseconnect HAL. The legacy RS1xxx.h header differs in subtle ways.
This PR fixes an inconsistency in the definition of __NVIC_PRIO_BITS between Zephyr and the Wiseconnect HAL leading to compiler errors when using certain HAL functions (#include-ing both Zephyr and Wiseconnect headers in the same file).

soc: silabs: siwg917: Include correct device header

---

boards/silabs/radio_boards/siwx917_rb4338a/siwx917_rb4338a.dts
boards/silabs/radio_boards/siwx917_rb4338a/siwx917_rb4338a.yaml
drivers/gpio/CMakeLists.txt
drivers/gpio/Kconfig
drivers/gpio/Kconfig.siwx917
drivers/gpio/gpio_silabs_siwx917.c
drivers/gpio/gpio_silabs_siwx917_uulp.c
dts/arm/silabs/siwg917.dtsi
dts/bindings/gpio/silabs,siwx917-gpio-port.yaml
dts/bindings/gpio/silabs,siwx917-gpio-uulp.yaml
dts/bindings/gpio/silabs,siwx917-gpio.yaml
tests/drivers/gpio/gpio_basic_api/boards/siwx917_rb4338a.overlay
west.yml

Implement GPIO driver for HP, ULP and UULP GPIOs.
This PR enables GPIO, and implements functional interrupt handling for all 3 GPIO modules.
TODO:
Inputs are very welcome on the above points.

drivers: gpio: siwx917: Add GPIO driver

---

boards/silabs/radio_boards/siwx917_rb4338a/siwx917_rb4338a.dts
boards/silabs/radio_boards/siwx917_rb4338a/siwx917_rb4338a.yaml
dts/arm/silabs/siwg917.dtsi
soc/silabs/silabs_siwx917/siwg917/soc.c

Add snps,designware-i2c compatibility for I2C peripherals.  
Enable I2C clocks in soc.c for now, pending proper implementation of clock control.  
Add pinctrl configuration for Si7021 sensor on rb4338a board.

soc: silabs: siwx917: Enable I2C

---

soc/silabs/silabs_siwx917/siwg917/Kconfig
soc/silabs/silabs_siwx917/siwg917/Kconfig.defconfig

soc: silabs: siwx917: Define flash mode in Kconfig file

---

drivers/wifi/siwx917/siwx917_wifi.c

The Zephyr stack does not update net_context state when CONFIG_NET_OFFLOAD=y. However, this field is still used in some not-offloaded operations (eg. poll()).
So, update net_context state manually.
Reported-by: Tibor Laczko <tibor.laczko@silabs.com>

drivers: siwx917_wifi: Update net_context state

---

.github/workflows/do_not_merge.yml

This allows us to fail CI if a DNM label is set. It's also preparation for a manifest workflow which can set the label automatically when the manifest points at a pull request rather than an actual commit in a module.

github: workflows: Add a Do Not Merge workflow

---

west.yml

Commit 99b1b03 ("manifest: Update Zephyr and HAL revisions") depended on a PR on hal_silabs. Unfortunately, it has been merged without updating the occurrence to this repo.
Fixes: 99b1b03 ("manifest: Update Zephyr and HAL revisions")

manifest: Fix HAL revision

---

CODEOWNERS

The usernames were missing the @ character.

CODEOWNERS: Fix user references

---

dts/bindings/bluetooth/silabs,bt-hci-siwx917.yaml
west.yml

This update requires updating the siwx917 Bluetooth HCI devicetree binding as well, since the format for bt-hci-bus and bt-hci-quirks properties has changed.

manifest: Update to latest upstream version

---

.github/workflows/build.yml
.github/workflows/upstream-build.yml
drivers/CMakeLists.txt
drivers/entropy/CMakeLists.txt
drivers/entropy/Kconfig
drivers/entropy/Kconfig.siwx917
drivers/entropy/entropy_silabs_siwx917.c
dts/arm/silabs/siwg917.dtsi
dts/bindings/rng/silabs,siwx917-rng.yaml
west.yml

This work is inspired of the Tibor's work.
This PR also align build.yml and upstream-build.yml.

Add RNG driver

---

soc/silabs/silabs_siwx917/siwg917/Kconfig.defconfig

Commit a448c72 ("soc: silabs: siwg917: Get rid of siwx917_isp_prepare.py") allows to flash the device using the .hex file. However, the .hex file was not build by default.
Fixes: a448c72 "soc: silabs: siwg917: Get rid of siwx917_isp_prepare.py"

soc: silabs: siwg917: Device needs .hex firmware

---

README.md

The west tool has a dedicated command now days for installing the latest Zephyr SDK version. Just refer to that instead of anything more complicated.

README: Update SDK installation instructions

---

.github/workflows/build.yml
.github/workflows/compliance.yml
.github/workflows/upstream-build.yml
west.yml

We want the workflows to fail for these steps, so remove continue-on-error.

github: workflows: Remove continue-on-error

---

README.md

Add a status badge to indicate whether the upstream daily build is passing or not.

README: Add status badge for upstream daily build

---

.github/workflows/build.yml
.github/workflows/upstream-build.yml
boards/silabs/radio_boards/siwx917_rb4338a/board.cmake
soc/silabs/silabs_siwx917/CMakeLists.txt
soc/silabs/silabs_siwx917/siwx917_isp_prepare.py

Commander is able to flash .hex file, but only the one generated by
siwx917_isp_prepare.py. The common .hex file, generated from the .elf
file are not supported.
So, restore the original behavior.

Restore rps build

---

README.md

The previous version only mentioned the important steps. This new
version give more details. Especially, it should allow the user to setup
a Docker image by just copy-pasting the code examples.
This documentation is still a summary of commands that can be found in
the Zephyr documentation. The idea is underline Silabs specific pitfalls
while keeping the ratio maintenance effort/covered cases low. So, for
now, this documentation only cover Docker/WSL/Linux.
Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

README: Improve "Install" and add "Troubleshooting"

---

west.yml

Update the west manifest to point at the Zephyr 4.0.0 release.

manifest: Update to Zephyr 4.0.0

---

drivers/bluetooth/hci/Kconfig.siwx917

With a recent upstream change related to removing TinyCrypt support, the HCI drivers need to make sure the top-level entropy driver option is enabled.

drivers: bluetooth: siwx917: Fix missing ENTROPY_GENERATOR selection

---

CODEOWNERS

There's now a dedicated Zephyr maintainers team, so use that.

CODEOWNERS: Update to use the new maintainers team

---

.github/workflows/upstream-build.yml

Add a new Bluetooth Observer role test case, and at the same time consolidate the various test & platform options into a single twister invocation. The observer test is useful since it doesn't enable SMP, and would have helped catch a regression for EFR32 platforms.
https://github.com/zephyrproject-rtos/zephyr/issues/82569
https://github.com/zephyrproject-rtos/zephyr/pull/82575

github: workflows: Add a Bluetooth observer test case

---

.github/workflows/upstream-build.yml

This updates the manifest in the upstream build workflow before setting up the Zephyr project. This way the manifest is correct from the very beginning, speeding up the setup process. The manifest is also updated using a YAML processor, which is more robust.

github: workflows: Refactor upstream build workflow

---

.github/workflows/build.yml

Commit 2208911 ("github: workflows: Add a Bluetooth observer test case") adds a new test to the nightly CI.
This patch tries to keep build.yml and upstream-build.yml in sync.

github: workflows: Align build.yml with upstream-build.yml

---

west.yml

Update to a new hal_silabs which contains cherry-picked commits from the upstream HAL tree. In particular, this includes SiSDK 2024.12. Also update the main tree reference so we get the changes needed to build with the new SiSDK version.

manifest: Update to new HAL

---

drivers/wifi/siwx917/siwx917_wifi.c

This PR fixes the handling of active and passive scan configurations in the siwx917 Wi-Fi driver, ensuring it respects user-provided scan options. Additionally, it adds support for direct SSID scanning, allowing users to scan for a specific SSID by providing it directly in the scan configuration.

Fix Wi-Fi Scan Configuration and Add Direct SSID Scanning Support for siwx917

---

drivers/wifi/siwx917/siwx917_wifi.c

Modified a condition in **siwx917_send** API to allow the raw packets for a max frame size of 1514 bytes. the present check has 1500 which limits to IP MTU and does not allow the network packets with a payload of 1460 bytes

drivers: wifi: siwx917: Fix support for frames > 1460 bytes

---

drivers/wifi/siwx917/Kconfig.siwx917
drivers/wifi/siwx917/siwx917_wifi.c
drivers/wifi/siwx917/siwx917_wifi.h

This commit adds support for the following scan functionalities
- Single and multi-channel scan
- Direct SSID scan
- Dwell time configuration for both active and passive scans
- Maximum BSS count configuration for the 2.4 GHz band
Since the device operates solely on the 2.4 GHz frequency band, this enhancement enables it to send probe requests and listen for beacon frames on specified channels, improving scan efficiency and customization.

drivers: wifi: siwx917: Add support for advanced scan options

---

west.yml

The nightly upstream build just started failing because of stuff that's been merged in the latest upstream hal_silabs. Update that reference, and also update the Zephyr main tree in the same go.

manifest: Update hal_silabs and zephyr to latest upstream versions

---

west.yml

Update to latest hal_silabs and zephyr revisions. This should also (again) fix the upstream build workflow.

manifest: Update to latest upstream revisions

---

west.yml

Update the mbedtls module to the latest fork of Zephyr's mbedtls fork, applying accelerator patches from SiSDK 2025.6.0.

manifest: Update mbedtls module

---

samples/wifi_ble_coex_demo/README.rst
samples/wifi_provisioning_over_ble/README.rst

Documented that the application thread must run at a lower priority than the Wi-Fi command handling threads to ensure smooth operation.

doc: Add guidelines for application thread priority

---

modules/hal_silabs/simplicity_sdk/inc/sli_psec_osal_zephyr.h

The SE mailbox priority must be lower than the base priority to ensure mutual exclusion. Interpret the Devicetree priority value as for a normal interrupt, not a zero-latency interrupt.
This issue was masked by the mailbox priority previously being 3 in SoC Devicetree files, which made it have a normal priority despite being interpreted as a zero-latency interrupt.

modules: hal_silabs: Set correct SE mailbox priority
